name: Deploy to Fly.io Staging

on:
  push:
    branches: ['fly/deploy-staging']
  workflow_dispatch:
    inputs:
      version:
        description: "Image version to deploy (e.g. v1.2.3)"
        required: false
        default: latest
        type: string

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Set image tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.version }}" ]; then
            echo "tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      # Create Fly.io app if it doesn't exist
      - name: Create App and Set Secrets
        run: |
          if ! flyctl apps list | grep -q petstore-ui-staging; then
            flyctl apps create --name petstore-ui-staging --auto-confirm
          else
            flyctl apps list
            echo "App petstore-ui-staging already exists, skipping creation."
          fi

          flyctl secrets set --stage API_KEY=${{ secrets.API_KEY }} -c .fly/staging/fly.toml

        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Deploy using the pre-built GHCR image
      - name: Deploy App to Fly.io
        run: |
          flyctl deploy \
            --config .fly/staging/fly.toml \
            --image ghcr.io/ramonalcantaraarceo/petstore-ui:${{ steps.set_tag.outputs.tag }} \
            --remote-only \
            --debug \
            --verbose

          flyctl scale count 1 -y -c .fly/staging/fly.toml

          if ! flyctl certs list -c .fly/staging/fly.toml | grep -q petstore-ui-staging.ramon-alcantara.work; then
            flyctl certs create petstore-ui-staging.ramon-alcantara.work --app petstore-ui-staging

          else
            echo "App petstore-ui-staging already has certificate defined, skipping creation."
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
