name: Deploy to Fly.io Dev

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image tag to deploy (e.g. v1.2.3); defaults to 'latest'"
        required: false
        type: string

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Install flyctl
      - uses: superfly/flyctl-actions/setup-flyctl@v1

      # Determine image tag
      - name: Set image tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.version }}" ]; then
            echo "tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Create Fly.io app if it doesn't exist
        run: |
          if ! flyctl apps list | grep -q petstore-ui-dev; then
            flyctl apps create --name petstore-ui-dev --auto-confirm

          else
            flyctl apps list
            echo "App petstore-ui-dev already exists, skipping creation."
          fi

          if ! flyctl secrets list -c .fly/dev/fly.toml | grep -q API_KEY; then
            flyctl secrets set --stage API_KEY=${{ secrets.API_KEY }} -c .fly/dev/fly.toml

          else
            echo "App petstore-ui-dev already has API_KEY secret defined, skipping creation."
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Deploy using the pre-built GHCR image
      - name: Deploy to Fly.io
        run: |
          flyctl deploy \
            --config .fly/dev/fly.toml \
            --image ghcr.io/ramonalcantaraarceo/petstore-ui:${{ steps.set_tag.outputs.tag }} \
            --remote-only \
            --verbose

          flyctl scale count 1 -y -c .fly/dev/fly.toml

          if ! flyctl certs list -c .fly/dev/fly.toml | grep -q petstore-ui-dev.ramon-alcantara.work; then
            flyctl certs create petstore-ui-dev.ramon-alcantara.work --app petstore-ui-dev

          else
            echo "App petstore-ui-dev already has certificate defined, skipping creation."
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
