name: Deploy Review App
on:
  # Run this workflow on every PR. The job will filter for head branches starting with 'fly/'.
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  # Set these to your Fly.io organization and preferred region.
  FLY_REGION: iad
  FLY_ORG: personal

jobs:
  remove_environment_app:
    name: Remove GH Environment
    if: startsWith(github.head_ref, 'fly/') &&  github.event.action == 'closed'
    runs-on: ubuntu-latest

    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    steps:
      - name: Get code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Remove PR app from Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.5.0
        with:
          config: .fly/pr/fly.toml
          name: pr-${{ github.event.number }}-ramonalcantaraarceo-${{ github.event.repository.name }}

      - name: Create GitHub App token
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@v3.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          environment: pr-${{ github.event.number }}

  review_app:
    name: Deploy PR App to Fly.io
    if: startsWith(github.head_ref, 'fly/') &&  github.event.action != 'closed'
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Create a GitHub deployment environment per review app.
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Get code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.5.0
        with:
          config: .fly/pr/fly.toml
          name: pr-${{ github.event.number }}-ramonalcantaraarceo-${{ github.event.repository.name }}
          secrets: API_KEY=${{ secrets.PR_API_KEY }}
